/** 事件台文案（zh/en）。走既有 I18nProvider 的 locale；只在本目录使用，不改共享字典。**文案不写涨跌、不预测。** */
import type { Locale } from "@/lib/i18n";
import { reasonText as baseReasonText } from "@/lib/reasons";

type Pair = { zh: string; en: string };
const C = {
  title: { zh: "我的事件台", en: "My Event Desk" },
  subtitle: { zh: "接下来哪些事件涉及我的持仓与运行中的任务？只列与你相关的；证据不足一律等待，不伪装。", en: "Which upcoming events touch my holdings and running tasks? Only what concerns you; insufficient evidence always means wait, never pretend." },
  owner: { zh: "钱包地址", en: "Wallet address" },
  owner_ph: { zh: "0x… 连接钱包或粘贴地址", en: "0x… connect a wallet or paste an address" },
  horizon: { zh: "时间范围", en: "Horizon" },
  hours: { zh: "小时", en: "h" },
  refresh: { zh: "刷新", en: "Refresh" },
  loading: { zh: "读取中…", en: "Loading…" },
  need_owner: { zh: "先连接钱包或填入地址，事件台按地址列出与你相关的事件。", en: "Connect a wallet or enter an address; the desk lists events relevant to that address." },
  unreachable: { zh: "事件服务不可达。不用回放冒充实时——请稍后再试。", en: "Event service unreachable. No replay is shown as live — try again later." },
  timeout: { zh: "事件服务 30 秒内没有回应。这里不放替代内容，请重试。", en: "The event service did not answer within 30 s. Nothing is shown in its place; try again." },
  retry: { zh: "重试", en: "Retry" },
  disabled: { zh: "事件台未启用（AGENT_C6_ENABLED=false）或服务未部署本能力。", en: "Event desk is disabled (AGENT_C6_ENABLED=false) or not deployed on this service." },
  holdings: { zh: "持仓", en: "Holdings" },
  tasks: { zh: "任务", en: "Tasks" },
  unavailable: { zh: "不可用", en: "unavailable" },
  not_ready: { zh: "未就绪", en: "not ready" },
  as_of: { zh: "截至", en: "as of" },
  generated: { zh: "生成于", en: "Generated" },
  empty: { zh: "这个范围内没有与你相关的事件。这是如实的空，不是故障。", en: "No events relevant to you in this range. An honest empty list, not a failure." },
  related: { zh: "与你相关", en: "Relevant to you" },
  universe: { zh: "已支持资产的其它事件", en: "Other events on supported assets" },
  rel_company_direct: { zh: "公司事件 · 直接关联", en: "Company event · direct" },
  rel_user_rule: { zh: "你的规则约束", en: "Your rule applies" },
  rel_macro_research: { zh: "宏观 · 研究关联", en: "Macro · research link" },
  macro_note: { zh: "宏观事件只标注可能相关，供研究参考；不把关联说成必然的方向。", en: "Macro events are flagged as possibly related, for research only; a link is not a claim of direction." },
  rv_holding_and_task: { zh: "持仓 + 任务", en: "holding + task" },
  rv_holding: { zh: "持仓", en: "holding" },
  rv_task: { zh: "任务", en: "task" },
  rv_universe: { zh: "仅资产", en: "asset only" },
  kind_EARNINGS: { zh: "财报", en: "Earnings" },
  kind_CORPORATE_ACTION: { zh: "公司行动", en: "Corporate action" },
  kind_MACRO_TIER1: { zh: "宏观 T1", en: "Macro T1" },
  kind_MACRO_TIER2: { zh: "宏观 T2", en: "Macro T2" },
  kind_FED_SPEECH: { zh: "联储讲话", en: "Fed speech" },
  kind_FED_BLACKOUT: { zh: "联储静默期", en: "Fed blackout" },
  kind_MARKET_HOLIDAY: { zh: "休市", en: "Market holiday" },
  kind_EARLY_CLOSE: { zh: "提前收盘", en: "Early close" },
  st_estimated: { zh: "估计", en: "estimated" },
  st_confirmed: { zh: "已确认", en: "confirmed" },
  st_revised: { zh: "已改期", en: "revised" },
  st_cancelled: { zh: "已取消", en: "cancelled" },
  st_released: { zh: "已发布", en: "released" },
  precision_exact: { zh: "时段锚点", en: "session anchor" },
  precision_day: { zh: "仅日期，无具体时刻", en: "date only, no time" },
  precision_estimate: { zh: "估计日期", en: "estimated date" },
  hint_bmo: { zh: "盘前", en: "before open" },
  hint_amc: { zh: "盘后", en: "after close" },
  hint_dmh: { zh: "盘中", en: "during hours" },
  revision: { zh: "修订", en: "rev" },
  revised_from: { zh: "原定", en: "was" },
  source: { zh: "来源", en: "source" },
  first_known: { zh: "首次可知", en: "first known" },
  assets: { zh: "相关资产", en: "Assets" },
  your_holding: { zh: "你的持仓", en: "your balance" },
  no_holding_data: { zh: "持仓数据不可用", en: "holdings unavailable" },
  tasks_hit: { zh: "命中的任务", en: "Tasks affected" },
  no_task_data: { zh: "任务数据不可用（任务服务未就绪）", en: "task data unavailable (task service not ready)" },
  no_task_hit: { zh: "没有任务受影响", en: "no task affected" },
  effect_wait: { zh: "按规则等待", en: "wait by rule" },
  effect_recheck: { zh: "需要重估", en: "recheck" },
  effect_pause_issuance: { zh: "暂停签发", en: "issuance paused" },
  effect_none: { zh: "无影响", en: "no effect" },
  window: { zh: "窗口", en: "window" },
  next_check: { zh: "下次检查", en: "next check" },
  blockers: { zh: "为什么还在等", en: "Why still waiting" },
  needs_choice: { zh: "需要你选择", en: "your choice needed" },
  action_view_evidence: { zh: "查看依据", en: "View evidence" },
  action_create_watch_task: { zh: "创建观察任务", en: "Create watch task" },
  action_keep_plan: { zh: "保持现计划", en: "Keep plan" },
  action_wait_by_rule: { zh: "按已有规则等待", en: "Wait by rule" },
  action_pause_issuance: { zh: "暂停后续签发", en: "Pause issuance" },
  action_preview_new_plan: { zh: "预览新计划", en: "Preview new plan" },
  action_na: { zh: "此事件不适用", en: "not applicable here" },
  pick_task: { zh: "作用于任务", en: "Apply to task" },
  new_task: { zh: "（新建 SIMULATION 观察任务）", en: "(new SIMULATION watch task)" },
  task_service_not_ready: { zh: "任务服务未就绪", en: "Task service not ready" },
  whole_day: { zh: "整日等待", en: "Wait the whole day" },
  ignore_event: { zh: "忽略此事件（保持现计划）", en: "Ignore this event (keep plan)" },
  evidence_n: { zh: "条证据", en: "evidence record(s)" },
  sim_only: { zh: "仅模拟：不签证明、不执行", en: "Simulation only: signs nothing, executes nothing" },
  no_exec: { zh: "这些动作只产生建议或草案，不会发出任何执行。", en: "These actions produce suggestions or drafts only; nothing is executed." },
  coverage_h: { zh: "财报覆盖与公司行动", en: "Earnings coverage & corporate actions" },
  coverage_p: { zh: "财报日历源：Finnhub（源无确认字段，一律「估计」）。未覆盖的资产显示「未知」，不等于「无财报」。", en: "Earnings calendar source: Finnhub (no confirmation field; always \"estimated\"). Uncovered assets show \"unknown\", which is not \"no earnings\"." },
  cov_covered: { zh: "已覆盖", en: "covered" },
  cov_unknown: { zh: "未知", en: "unknown" },
  cov_unavailable: { zh: "源不可用", en: "source unavailable" },
  cov_not_probed: { zh: "尚未探测", en: "not probed yet" },
  corp_actions: { zh: "公司行动（拆股 / 分红 / 停牌）", en: "Corporate actions (splits / dividends / halts)" },
  corp_not_connected: { zh: "未接入：只有 v5 的乘数证据（登记基准 1 代币 = 股数）。不显示「未发生」。", en: "Not connected: only the v5 multiplier evidence (registry baseline shares per token). Never shown as \"none happened\"." },
  last_probed: { zh: "最近探测", en: "last probed" },
  show_more: { zh: "展开", en: "Show" },
  hide: { zh: "收起", en: "Hide" },
  /* V-34 */
  more: { zh: "更多", en: "More" },
  less: { zh: "收起动作", en: "Fewer" },
  open_task: { zh: "查看任务", en: "Open task" },
  dev_view: { zh: "开发者视图", en: "Developer view" },
  na_tasks_not_ready: { zh: "任务服务未就绪，作用于任务的动作暂不可用", en: "task service not ready, so task actions are unavailable" },
  na_no_task: { zh: "没有任务受这个事件影响，作用于任务的动作不适用", en: "no task is affected by this event, so task actions do not apply" },
  na_generic: { zh: "此事件不适用", en: "not applicable to this event" },
  evidence_none: { zh: "暂无证据记录。", en: "No evidence record yet." },
  evidence_none_estimated: { zh: "暂无证据：这是估计日期，来源还没有发布正式记录。", en: "No evidence yet: this is an estimated date; the source has not published a record." },
  preview_no_auth: { zh: "只是预览：不改真实任务、不写任何授权。", en: "Preview only: the real task and your authorization are untouched." },
  eff_evidence: { zh: "依据", en: "evidence" },
  eff_created: { zh: "已创建观察任务", en: "watch task created" },
  eff_attached: { zh: "已挂到任务", en: "attached to task" },
  eff_draft: { zh: "草案", en: "draft" },
  eff_kept: { zh: "保持现计划", en: "plan kept" },
  eff_wait: { zh: "按规则等待", en: "waiting by rule" },
  eff_needs_choice: { zh: "需要你选择", en: "your choice needed" },
  eff_paused: { zh: "已暂停签发", en: "issuance paused" },
  eff_preview: { zh: "预览", en: "preview" },
  eff_not_ready: { zh: "任务服务未就绪", en: "task service not ready" },
  eff_invalid: { zh: "不合法", en: "invalid" },
} satisfies Record<string, Pair>;

export type CopyKey = keyof typeof C;
export function copy(locale: Locale): (k: CopyKey) => string {
  return (k) => C[k][locale];
}

/** v6 原因码文案（与 verify-service impacts/reasonText.ts 同义）；其余回退 lib/reasons.ts */
const R6: Record<string, Pair> = {
  EARNINGS_WINDOW_ACTIVE: { zh: "处于你设定的财报窗口内：财报前后暂停签发，等窗口结束后再评估。", en: "Inside your earnings window: issuance pauses around the report and resumes after the window ends." },
  EVENT_WINDOW_ACTIVE: { zh: "处于你设定的事件窗口内：窗口结束前不签发。", en: "Inside your event window: nothing is issued until the window closes." },
  EVENT_DATE_UNCERTAIN: { zh: "该事件只有日期、没有具体时刻。你没有预选「整日等待」，需要你选择：整日等待，或忽略此事件。服务不会替你补一个时刻。", en: "This event has a date but no time. You have not pre-selected whole-day waiting; choose whole-day wait or ignore. The service will not invent a time." },
  EARNINGS_COVERAGE_UNKNOWN: { zh: "财报日历源未覆盖该资产：不能断言「无财报」，按未知处理。", en: "The earnings calendar source does not cover this asset: treated as unknown, not as \"no earnings\"." },
  REFERENCE_STALE: { zh: "股票参考价尚未恢复为实时（仍是收盘/陈旧值）：财报窗口计时已结束也不买。", en: "The stock reference has not returned to live (still a close/stale value): the window timer ending is not enough to buy." },
  REFERENCE_MISSING: { zh: "没有可用的股票参考价：财报窗口计时已结束也不买。", en: "No stock reference is available: the window timer ending is not enough to buy." },
  PRICE_IMPACT_EXCEEDED: { zh: "链上报价的价格冲击超过你的上限：现在成交会明显吃亏，继续等待。", en: "On-chain price impact exceeds your limit: executing now would be costly, keep waiting." },
  PRICE_IMPACT_UNKNOWN: { zh: "链上报价的价格冲击未知，不当作 0：继续等待。", en: "On-chain price impact is unknown and is not treated as zero: keep waiting." },
  CONTEXT_UNAVAILABLE: { zh: "市场上下文不可用。", en: "Market context unavailable." },
};
export function reasonText6(code: string, locale: Locale): string {
  return R6[code]?.[locale] ?? baseReasonText(code, locale);
}
