[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
test = "test"
script = "script"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 800
evm_version = "cancun"
via_ir = true
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "forge-std/=node_modules/forge-std/src/",
]
fs_permissions = [{ access = "read", path = "./config" }]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 64
depth = 32
fail_on_revert = false

[rpc_endpoints]
xlayer = "${XLAYER_RPC_URL}"
xlayer_testnet = "${XLAYER_TESTNET_RPC_URL}"
